CREATE TABLE prestaciones(
   id     BIGINT  NOT NULL PRIMARY KEY 
  ,codigo VARCHAR(7)  NOT NULL
  ,prestacion VARCHAR(318) NOT NULL
);
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (1,'0301002','Acido fólico o folatos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (2,'0301003','Adenograma, mielograma, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (3,'0301006','Agregación plaquetaria con diferentes agonistas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (4,'0301007','Anticoagulantes circulantes o anticoagulante lúpico');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (5,'0301008','Antitrombina III');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (6,'0301011','Coagulación, tiempo de');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (7,'0301013','Tiempo de lisis del coágulo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (8,'0301014','Prueba de antiglobulina directa');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (9,'0301017','Deshidrogenasa glucosa-6-fosfato en eritrocitos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (10,'0301020','Tiempo de lisis de euglobulinas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (11,'0301021','Fibrinógeno');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (12,'0301022','Test de neutralización plaquetaria');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (13,'0301024','Factor V');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (14,'0301025','Factores VII, VIII, IX, X, XI, XII, XIII, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (15,'0301026','Ferritina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (16,'0301027','Fibrinógeno, productos de degradación del');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (17,'0301028','Fierro sérico');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (18,'0301029','Fierro, capacidad de fijación del (incluye fierro sérico)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (19,'0301030','Fierro, cinética del (cada determinación)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (20,'0301034','Clasificación sanguínea AB0 y RhD');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (21,'0301035','Haptoglobina cuantitativa');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (22,'0301036','Hematocrito (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (23,'0301038','Hemoglobina en sangre total (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (24,'0301040','Hemoglobina fetal cuantitativa en eritrocitos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (25,'0301041','Hemoglobina glicada A1c');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (26,'0301042','Hemoglobina plasmática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (27,'0301044','Electroforesis de hemoglobina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (28,'0301045','Hemograma (incluye recuentos de leucocitos y eritrocitos, hemoglobina, hematocrito, fórmula leucocitaria, características de los elementos figurados y velocidad de eritrosedimentación)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (29,'0301048','Hemosiderina medular');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (30,'0301049','Cuantificación de heparina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (31,'0301051','Identificación de anticuerpos irregulares eritrocitarios');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (32,'0301054','Metahemoglobina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (33,'0301059','Tiempo de protrombina (incluye INR, Razón Internacional Normalizada)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (34,'0301062','Recuento de basófilos (absoluto)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (35,'0301063','Recuento de eosinófilos (absoluto)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (36,'0301064','Recuento de eritrocitos, absoluto (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (37,'0301065','Recuento de leucocitos, absoluto (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (38,'0301066','Recuento de linfocitos (absoluto)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (39,'0301067','Recuento de plaquetas (absoluto)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (40,'0301068','Recuento de reticulocitos (absoluto o porcentual)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (41,'0301069','Recuento diferencial o fórmula leucocitaria (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (42,'0301070','Resistencia globular osmótica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (43,'0301072','Tiempo de sangría (no incluye dispositivo asociado)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (44,'0301082','Transferrina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (45,'0301083','Trombina, tiempo de');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (46,'0301085','Tromboplastina, tiempo parcial de (TTPA, TTPK o similares)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (47,'0301086','Velocidad de eritrosedimentación (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (48,'0301089','Factor Von Willebrand antigénico (FVW:Ag)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (49,'0301090','Factor Von Willebrand antigénico Cofactor Ristocetina (FVW:CoRis)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (50,'0301091','Proteína C funcional');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (51,'0301092','Proteína S');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (52,'0301093','Resistencia a la Proteína C activada');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (53,'0301094','Estudio de la hemoglobinuria paroxística nocturna (HPN) por citometría de flujo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (54,'0301095','Dímero-D');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (55,'0301096','Procalcitonina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (56,'0301097','Inhibidor de factor de la coagulación');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (57,'0301098','Secreción plaquetaria con diferentes agonistas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (58,'0301099','Tiempo de veneno de víbora de Russell diluído');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (59,'0302001','Cuerpos cetónicos en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (60,'0302002','Acido cítrico');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (61,'0302004','Lactato en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (62,'0302005','Acido úrico, en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (63,'0302008','Amilasa, en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (64,'0302009','Aminoácidos, cualitativo en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (65,'0302010','Amonio');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (66,'0302070','Apolipoproteínas (A1, B u otras)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (67,'0302011','Bicarbonato (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (68,'0302012','Bilirrubina total (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (69,'0302013','Bilirrubina total y conjugada');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (70,'0302015','Calcio en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (71,'0302017','Caroteno');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (72,'0302018','Caroteno, prueba de sobrecarga de, además 2 códigos 03-07-011 o 03-07-012.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (73,'0302019','Ceruloplasmina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (74,'0302020','Cobre en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (75,'0302067','Colesterol total (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (76,'0302068','Colesterol HDL (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (77,'0302021','Colinesterasa en suero o plasma');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (78,'0302023','Creatinina en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (79,'0302024','Clearance de creatinina (proc.aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (80,'0302025','Creatinquinasa CK - MB  actividad');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (81,'0302026','Creatinquinasa CK - total');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (82,'0302027','Troponina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (83,'0302030','Deshidrogenasa láctica total (LDH)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (84,'0302031','Deshidrogenasa láctica total (LDH), con separación de isoenzimas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (85,'0302032','Electrolitos plasmáticos (sodio, potasio, cloro) c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (86,'0302033','Enzima convertidora de angiotensina I');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (87,'0302034','Perfil lipídico (incluye mediciones de colesterol total, HDL-colesterol y triglicéridos con estimaciones por fórmula de LDL-colesterol, VLDL-colesterol y colesterol no-HDL)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (88,'0302035','Fármacos y/o drogas; niveles plasmáticos de (alcohol, anorexígenos, antiarrítmicos, antibióticos, antidepresivos, antiepilépticos, antihistamínicos, antiinflamatorios y analgésicos, estimulantes respiratorios, tranquilizantes mayores y menores, etc.) c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (89,'0302036','Fenilalanina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (90,'0302039','Fosfatasas alcalinas con separación de isoenzimas hepáticas, intestinales, óseas c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (91,'0302040','Fosfatasas alcalinas totales');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (92,'0302042','Fósforo (fosfatos) en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (93,'0302043','Galactosa');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (94,'0302045','Gamma glutamiltranspeptidasa (GGT)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (95,'0302046','Gases y equilibrio ácido base en sangre (incluye: pH, O2, CO2, exceso de base y bicarbonato), todos o cada uno de los parámetros');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (96,'0302047','Glucosa en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (97,'0302048','Glucosa, Prueba de Tolerancia a la Glucosa Oral (PTGO), (dos determinaciones; no incluye la glucosa que se administra; incluye el valor de las dos tomas de muestras)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (98,'0302050','Adenosindeaminasa en sangre u otro fluído biológico.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (99,'0302052','Leucinaminopeptidasa (LAP)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (100,'0302053','Lipasa en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (101,'0302055','Litio en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (102,'0302056','Magnesio en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (103,'0302057','Nitrógeno ureico y/o urea, en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (104,'0302058','Osmolalidad en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (105,'0302075','Perfil Bioquímico (determinación automatizada de 12 parámetros)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (106,'0302061','Proteínas, electroforesis (incluye cód. 03-02-060)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (107,'0302076','Perfil Hepático (incluye tiempo de protrombina, bilirrubina total y conjugada, fosfatasas alcalinas totales, GGT, transaminasas GOT/AST y GPT/ALT)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (108,'0302063','Transaminasas, oxalacética (GOT/AST), Pirúvica (GPT/ALT), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (109,'0302064','Triglicéridos en sangre (proc.aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (110,'0302066','Xilosa, prueba de absorción (no incluye la xilosa que se administra)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (111,'0302077','Vitamina B12 por inmunoensayo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (112,'0302078','25 OH Vitamina D Total por inmunoensayo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (113,'0302080','Vitamina B6 por HPLC');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (114,'0302081','Calcio iónico. Incluye medición de pH método ión selectivo. No incluye Point of Care Testing POCT');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (115,'0302082','Fenilalanina Cuantitativa en Gotas de Sangre Seca');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (116,'0302083','Carboxihemoglobina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (117,'0302084','Plomo en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (118,'0302085','Prealbumina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (119,'0302086','Homocisteína');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (120,'0302100','Proteínas totales en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (121,'0302101','Albúminas en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (122,'0303001','Adenocorticotrofina (ACTH)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (123,'0303002','Aldosterona');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (124,'0303003','Androstenediona');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (125,'0303004','Angiotensina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (126,'0303006','Cortisol');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (127,'0303007','Crecimiento, hormona de (HGH) (somatotrofina)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (128,'0303008','Dehidroepiandrosterona sulfato (DHEA-S)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (129,'0303009','Eritropoyetina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (130,'0303012','Gastrina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (131,'0303014','Gonadotrofina coriónica, sub-unidad beta (cuantificación)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (132,'0303015','Hormona folículo estimulante (FSH)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (133,'0303016','Hormona luteinizante (LH)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (134,'0303047','IGF1 o Somatomedina - C (Insuline Like Growth Factor)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (135,'0303048','IGFBP3, IGFBP1 (Insulin Like Growth Factor Binding Proteins)  c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (136,'0303017','Insulina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (137,'0303031','Insulina, curva de (mínimo dos determinaciones e incluye todas las tomas de muestra necesarias. No incluye la glucosa que se administra)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (138,'0303018','Parathormona, hormona Paratiroídea o PTH.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (139,'0303019','Progesterona');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (140,'0303020','Prolactina (PRL)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (141,'0303021','Renina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (142,'0303046','SHBG (Sex-Hormone Binding Globulin)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (143,'0303022','Testosterona en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (144,'0303023','Testosterona libre en sangre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (145,'0303123','Índice androgénico (incluye Testosterona Total y SHBG)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (146,'0303024','Tiroestimulante (TSH), hormona (Adulto, niño o R.N.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (147,'0303025','Tiroglobulina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (148,'0303026','Tiroxina libre (T4L)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (149,'0303027','Tiroxina o tetrayodotironina (T4)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (150,'0303028','Triyodotironina (T3)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (151,'0303029','17 - Hidroxiprogesterona');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (152,'0303030','Estradiol (17-Beta)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (153,'0303049','Catecolaminas en sangre (incluye medición de Adrenalina, Noradrenalina y Dopamina por separado por métodos cromatográficos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (154,'0303052','Peptido C');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (155,'0303053','Calcitonina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (156,'0303054','Inhibina B');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (157,'0303055','NT-Pro BNP O BNP');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (158,'0303057','Triyodotironina Libre (T3 libre)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (159,'0303033','Angiotensina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (160,'0303035','Cortisol libre urinario');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (161,'0303039','Gonadotrofina coriónica, sub-unidad Beta; titulación por (Elisa; RIA o IRMA; Quimioluminiscencia u otra técnica)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (162,'0303050','Metanefrinas urinarias (incluye determinación de Metanefrina y Normetanefrina por separado por métodos cromatográficos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (163,'0303051','Catecolaminas urinarias (incluye medición de Adrenalina, Noradrenalina y Dopamina por separado por métodos cromatográficos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (164,'0303056','Cortisol salival');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (165,'0304001','Cariotipo en sangre por cultivo de linfocitos (incluye mínimo 25 mitosis con bandeo G y eventualmente Q, R, C, NOR) (montaje de 3 metafases bandeadas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (166,'0304002','Cariotipo con técnicas especiales (incluye muestra de sangre o de médula ósea, tratamiento con FUDR, bromuro de etidio, medio deficiente en ácido fólico)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (167,'0304003','Cariotipo en fibroblastos por cultivo de trofoblasto, líquido amniótico, piel u otros bandeos G y eventualmente Q, R, C, NOR');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (168,'0304006','FISH Cromosomas X e Y');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (169,'0304007','Diagnóstico Genético Molecular: Displasia Tanatofórica tipo I y II');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (170,'0304008','Amplificación por PCR más análisis de fragmentos fluorescentes por electroforesis capilar (hasta 5 fragmentos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (171,'0304009','Estudio de deleciones y duplicaciones por amplificación múltiple de sondas dependiente de ligación (MLPA)  (1 o varios genes)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (172,'0304010','Estudio de deleciones y duplicaciones por amplificación múltiple de sondas dependiente de ligación (MLPA) más estudio de metilación o segundo set de sondas  (1 o varios genes)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (173,'0304011','FISH en frotis frescos de médula ósea, sangre, concentrado de células plasmáticas seleccionadas o corte de tejido en parafina, búsqueda de alteraciones adquiridas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (174,'0304012','Amplificación por PCR en tiempo real cuantitativo con sonda');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (175,'0304013','Amplificación de ADN por PCR convencional de 1 fragmento');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (176,'0304014','Amplificación por PCR más análisis por restricción enzimática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (177,'0305001','Alfa -1- antitripsina cuantitativa');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (178,'0305002','Alfa -2- macroglobulina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (179,'0305003','Alfa fetoproteínas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (180,'0305004','Tamizaje de Anticuerpos anti antígenos nucleares extractables (a- ENA: Sm, RNP, Ro, La, Scl- 70 y Jo- 1)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (181,'0305005','Anticuerpos antinucleares (ANA), antimitocondriales, anti DNA (ADNA), anti músculo liso, anticentrómero, u otros, c/u.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (182,'0305007','Anticuerpos específicos y otros autoanticuerpos (anticuerpos antitiroídeos: anticuerpos antimicrosomales y antitiroglobulinas y otros anticuerpos: prostático, espermios, etc.) c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (183,'0305008','Antiestreptolisina O, por técnica de látex');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (184,'0305009','Antígeno carcinoembrionario (CEA)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (185,'0305070','Antígeno prostático específico');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (186,'0305170','Antígeno Ca 125, Ca 15-3 y Ca 19-9, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (187,'0305010','Beta-2-microglobulina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (188,'0305012','Complemento C1Q, C2, C3, C4, etc., c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (189,'0305013','Complemento hemolítico (CH 50)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (190,'0305014','Crioglobulinas, precipitación en frío (cualitativa) o cuantitativa c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (191,'0305019','Factor reumatoídeo por técnica de látex u otras similares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (192,'0305020','Factor reumatoídeo por técnica de Scat, Waaler Rose, nefelométricas y/o turbidimétricas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (193,'0305021','Inhibidor de C1Q, C2 y C3, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (194,'0305025','Inmunofijación de inmunoglobulina, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (195,'0305026','Inmunoglobulina IgA secretora');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (196,'0305027','Inmunoglobulinas IgA, IgG, IgM, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (197,'0305028','Inmunoglobulinas IgE, IgD total, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (198,'0305029','Inmunoglobulinas IgE, IgG específicas, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (199,'0305030','Proteína C reactiva por técnica de látex u otras similares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (200,'0305031','Proteína C reactiva por técnicas automatizadas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (201,'0305081','Anticuerpo antiendomisio (EMA, antimembrana basal glomerular (GBM), antireticulina, por IFI c/u.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (202,'0305181','Anticuerpos antitransglutaminasa (TTG)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (203,'0305082','Anticuerpos anticitoplasma de neutrófilos (ANCA), C-ANCA y P-ANCA, por IFI');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (204,'0305083','Determinación de isotipos de anticuerpos anticitoplasma de neutrófilos (G-M-A-C''3), por IFI, c/u.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (205,'0305084','Anticuerpos anticardiolipinas (IgG, IgM), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (206,'0305085','Anticuerpos anti LKM-1');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (207,'0305086','Anticuerpos contra péptidos deaminados de gliadina IgG e IgA');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (208,'0305098','Cromogranina A');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (209,'0305099','Péptido Cíclico Citrulinado, anticuerpos IgG');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (210,'0305104','Antigeno prostatico total y libre');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (211,'0305105','Anticuerpos anti-Beta 2 glicoproteina 1 (IgG, IgM), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (212,'0305035','Detección, identificación y titulación de crioaglutininas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (213,'0305036','Criohemolisinas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (214,'0305037','Digestión fagocítica nitroblue-tetrazolium cualitativo y cuantitativo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (215,'0305038','Fagocitosis: ingestión y digestión (killing) de levaduras por polimorfonucleares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (216,'0305039','Fagocitosis: ingestión y digestión (killing) de bacterias por polimorfonucleares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (217,'0305040','Inmunoadherencia de leucocitos macrófagos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (218,'0305041','Intradermorreacción (PPD, histoplasmina, aspergilina, u otros, incluye el valor del antígeno y reacción de control), c/u.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (219,'0305080','Estudio para hipersensibilidad retardada');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (220,'0305042','LIF o MIF');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (221,'0305044','Linfocitos B (rosetas EAC) y linfocitos T (rosetas E) c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (222,'0305047','Linfotoxinas humanas, detección de');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (223,'0305049','Transformación linfoblástica a drogas, análisis de transformación espontánea con estímulo inespecífico y con diferentes concentraciones de la droga en 1000 células');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (224,'0305089','Linfocitos B totales (CD19). Técnica Citometría de Flujo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (225,'0305091','Linfocitos T (CD3, CD4, CD8). Técnica Citometría de Flujo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (226,'0305092','Natural Killers (CD16, CD 56). Técnica Citometría de Flujo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (227,'0305093','Inmunofenotipo en Leucemias Agudas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (228,'0305094','Inmunofenotipo en Síndrome Linfoproliferativos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (229,'0305095','Inmunofenotipo en Síndrome Mielodisplásicos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (230,'0305096','Detección de Enfermedad Residual Mínima');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (231,'0305097','Cuantificación de células progenitoras hematopoyéticas CD 34');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (232,'0305110','Alocross Match Linfocitos T y Linfocitos B (Citometría De Flujo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (233,'0305111','Anticuerpo Anti HLA Clase I y II Screening (Luminex)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (234,'0305112','Autocrossmatch Linfocitos T y B   (Citometría De Flujo )');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (235,'0305113','Especificidad De Anticuerpos HLA  Con Antígenos Individuales Clase I  (Luminex)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (236,'0305114','Especificidad De Anticuerpos HLA  Con Antígenos Individuales Clase II (Luminex)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (237,'0305115','Estudio Receptor Trasplantado Con Donante Cadáver');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (238,'0305116','HLA-AB Tipificación (Biología Molecular)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (239,'0305117','HLA-ABDR Tipificación  (Biología Molecular)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (240,'0305118','HLA-B27 Tipificación (Biología Molecular)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (241,'0305119','HLA-C Tipificación  (Biología Molecular)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (242,'0305120','HLA-DP Tipificación  (Biología  Molecular)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (243,'0305121','HLA-DQ Tipificación (Biología Molecular)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (244,'0305122','HLA-DR Tipificación  (Biología Molecular)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (245,'0305123','Seroteca  Mensual y Mantención en Lista De Espera');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (246,'0306001','Baciloscopía por método de concentración');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (247,'0306002','Baciloscopía Ziehl-Neelsen, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (248,'0306004','prestacion directo al fresco, c/s tinción (incluye trichomonas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (249,'0306005','Tinción de Gram');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (250,'0306006','Ultramicroscopía (incluye toma de muestras)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (251,'0306102','Tinción de toluidina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (252,'0306007','Coprocultivo, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (253,'0306008','Cultivo corriente (excepto coprocultivo, hemocultivo y urocultivo) c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (254,'0306011','Urocultivo, recuento de colonias y antibiograma (cualquier técnica) (incluye toma de orina aséptica y frasco recolector) (no incluye recolector pediátrico ni sonda)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (255,'0306091','Hemocultivo automatizado. Incluye Antibiograma con CIM. 2 frascos (costo no incluido en el arancel)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (256,'0306093','Hemocultivo automatizado para Micobacterias.1 frasco (costo no incluido en el arancel)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (257,'0306101','Cultivo de Líquido de Cavidades Estériles en frasco de Hemocultivo  automatizado. Incluye Antibiograma con CIM. (1 frasco, costo no incluido en arancel).');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (258,'0306106','Hemocultivo automatizado para hongos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (259,'0306012','Cultivo para Anaerobios (incluye Cód. 03-06-008)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (260,'0306013','Cultivo para Bordetella');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (261,'0306014','Cultivo para Campylobacter, Yersinia, Vibrio, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (262,'0306016','Neisseria gonorrhoeae (gonococo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (263,'0306017','Cultivo para hongos (levaduras y filamentosos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (264,'0306117','Cultivo para dermatofitos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (265,'0306018','Cultivo para micobacterias (incluye bacilo de Koch)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (266,'0306019','Cultivo para Legionella');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (267,'0306022','Cultivo y Tipificación de micobacterias');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (268,'0306023','Cultivo mycoplasma y ureaplasma, c/u.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (269,'0306099','Streptococcus Grupo B/ agalactiae en embarazada por cultivo con medio selectivo y/o enriquecido.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (270,'0306100','Cultivo acelerado para Micobacterias');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (271,'0306025','Antibiograma Bacilo de Koch (cada fármaco)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (272,'0306026','Antibiograma Corriente (mínimo 10 fármacos) (en caso de urocultivo no corresponde su cobro; incluido en el valor 03-06-011)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (273,'0306027','Antibiograma de estudio de sensibilidad por dilución (CIM) (mínimo 6 fármacos) (en caso de urocultivo, no corresponde su cobro; incluido en el valor código 03-06-011)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (274,'0306028','Antifungigrama (mínimo 4 fármacos antihongos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (275,'0306090','Test rápido de detección de streptococcus grupo A (Pyogenes)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (276,'0306097','Chlamydia Trachomatis y Neisseria Gonorrhoeae detección por técnica de biología molecular');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (277,'0306098','Toxina Clostridium Difficile en deposiciones test rápido');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (278,'0306107','Pneumocystis Jirovecci por técnica de biología molecular en tiempo real');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (279,'0306118','Amplificación de DNA de Bordetella Pertussis  por técnica de biología molecular en tiempo real');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (280,'0306033','Brucella abortus, melitensis y suis, anticuerpos, por Aglutinación o Elisa');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (281,'0306034','Clamidias por inmunofluorescencia, peroxidasa, Elisa o similares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (282,'0306036','Mononucleosis, reacción de Paul Bunnell, Anticuerpos Heterófilos o similares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (283,'0306037','Mycoplasma IgG, IgM, c/u.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (284,'0306038','R.P.R.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (285,'0306039','Tíficas, reacciones de aglutinación  (Eberth H y O, paratyphi A y B) (Widal)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (286,'0306041','Treponema pallidum FTA - ABS, MHA-TP c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (287,'0306042','V.D.R.L.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (288,'0306094','Antígeno galactomanano');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (289,'0306119','Interferón Gamma TBC');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (290,'0306043','Artrópodos macroscópicos y microscópicos (imagos y/o pupas y/o larvas), diagnóstico de');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (291,'0306045','Coproparasitario seriado con técnica  para Cryptosporidium sp o para Diantamoeba fragilis (incluye los códigos 03-06-048 y/o 03-06-059 más aplicación de técnica de frotis con tinción tricrómica o tinción Ziehl-Neelsen en por lo menos 3 muestras, según corresponda)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (292,'0306046','Coproparasitario seriado para fasciola hepática (incluye diagnóstico de gusanos macroscópicos y prestacion microscópico de 10 muestras por método de Telemann y simultáneamente por técnica de Sedimentación rápida (Copa Cónica)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (293,'0306047','Coproparasitario seriado para Isospora y Sarcocystis (incluye diagnóstico de gusanos macroscópicos y prestacion  microscópico de 3 muestras separadas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (294,'0306048','Coproparasitológico seriado simple (incluye diagnóstico de gusanos macroscópicos y prestacion microscópico por concentración de tres muestras separadas método Telemann ) (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (295,'0306049','Diagnóstico de parásitos en jugo duodenal y/o bilis, prestacion macroscópico y microscópico (directo y/o concentración, c/s tinción)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (296,'0306050','Diagnóstico parasitario en exudados, secreciones y otros líquidos orgánicos, prestacion macro y microscópico de (incluye concentración y/o tinción cuando proceda), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (297,'0306051','Graham, prestacion de (incluye diagnóstico de gusanos macroscópicos y prestacion microscópico de 5 muestras separadas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (298,'0306052','Estudio de gusanos macroscópicos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (299,'0306053','Hemoparásitos, diagnóstico microscópico de (mínimo 10 frotis y/o gotas gruesas, c/s prestacion directo al fresco), cada sesión');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (300,'0306054','Hemoparásitos, diagnóstico por técnica de Microstrout o similar en hasta 10 tubos capilares, cada sesión (Chagas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (301,'0306056','Raspado de piel, prestacion microscópico de ("Acarotest"): de 6 a 10 preparaciones');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (302,'0306059','Coproparasitológico seriado simple (incluye diagnóstico de gusanos macroscópicos y prestacion microscópico por concentración de tres muestras separadas método PAFS) (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (303,'0306061','Parásitos IgG/IgM (Chagas, Hidatidosis, Toxocariasis y otros por Elisa o Inmunofluorescencia), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (304,'0306066','Inmunofluorescencia indirecta (toxoplasmosis, Chagas, amebiasis y otras), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (305,'0306095','Parásitos: determinación por reacción de polimerasa en cadena (PCR)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (306,'0306096','Parásitos: test rápido anticuerpos (Chagas y otros)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (307,'0306068','Aislamiento de virus (Adenovirus, Citomegalovirus, Enterovirus, Herpes, Influenza, Polio,Sarampión y otros), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (308,'0306069','Anticuerpos virales, determ. de (SARS CoV-2 IgM IgG), (adenovirus, citomegalovirus, herpes simple, rubéola, influenza  A y B; virus varicela-zoster; virus sincicial respiratorio; parainfluenza 1, 2 y 3; Epstein Barr y otros), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (309,'0306169','Anticuerpos virales, determ. de H.I.V.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (310,'0306070','Antígenos virales determ. de (adenovirus, citomegalovirus, herpes simple, rubéola, influenza y otros), (por cualquier técnica ej: inmunofluorescencia), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (311,'0306170','Antígenos virales determ. de rotavirus, por cualquier técnica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (312,'0306270','Antígenos virales determ. de virus sincicial, por cualquier técnica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (313,'0306074','Virus Hepatitis A, anticuerpos IgG, IgM o totales c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (314,'0306075','Virus hepatitis B, anticuerpo del antígeno E del');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (315,'0306076','Virus hepatitis B, anticore total del (anti HBc total)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (316,'0306078','Virus hepatitis B, antígeno E del (HBEAg)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (317,'0306079','Virus hepatitis B, antígeno de superficie (HBsAg)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (318,'0306080','Virus hepatitis B, anticore IgM del (anti HBc IgM)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (319,'0306081','Virus hepatitis C, anticuerpos de (anti HCV)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (320,'0306082','Reacción de Polimerasa en cadena (P.C.R.) en tiempo real, SARS  CoV-2, (incluye toma muestra hisopado nasofaríngeo).');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (321,'0306182','Reacción de Polimerasa en cadena (P.C.R.) en tiempo real, virus Influenza, virus Herpes, citomegalovirus, hepatitis C, mycobacteria TBC, c/u (incluye toma muestra hisopado nasofaríngeo).');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (322,'0306083','Citomegalovirus (CMV) shell vial aislamiento rápido');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (323,'0306084','Hepatitis B, carga viral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (324,'0306085','Hepatitis C, carga viral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (325,'0306086','VIH, carga viral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (326,'0306087','Virus Epstein Barr (VEB) carga viral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (327,'0306088','Polioma (BK) virus carga viral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (328,'0306109','VIH, Genotipificación antivirales');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (329,'0306110','PCR metapneumovirus');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (330,'0306111','HTLV I y II determinación de anticuerpos virales');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (331,'0306112','VIH, anticuerpos y antígenos virales, determ. de H.I.V.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (332,'0306113','VIH, reacción de polimerasa en cadena (P.C.R.) en líquido cefaloraquídeo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (333,'0306120','Panel viral diarrea por PCR (determinación de rotavirus, norovirus g1, norovirus g2, astrovirus, adenovirus)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (334,'0306121','Hanta virus, anticuerpos IgM test rápido');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (335,'0306122','Panel virus respiratorio molecular (15 a 17 virus) (adenovirus, VRS A, VRS B, parainfluenza 1,2,3,4, influenza a y b, influenza a H1N1, bocavirus, coronavirus (2 tipos), rinovirus, enterovirus.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (336,'0306123','Virus Papiloma Humano por PCR con genotipificación de papiloma de alto riesgo de Ca Cervico Uterino tipos 16 y 18');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (337,'0306271','Test rápido de detección de antígenos SARS-CoV-2 (incluye toma de muestra)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (338,'0307001','Dietilendiamina tetraacetato de sodio cromo (EDTA Cr 51)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (339,'0307002','Prueba de la sed (volumen, densidad, osmolalidad seriada en sangre y orina)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (340,'0307005','Reacción cutánea de parche c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (341,'0307006','Sobrecarga hídrica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (342,'0307007','Test del sudor (procedimiento completo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (343,'0307008','Vasopresina test o similares (incluye además mediciones de diuresis)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (344,'0307009','Arterial en adultos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (345,'0307010','Arterial en niños y lactantes');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (346,'0307011','Venosa en adultos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (347,'0307012','Venosa en niños y lactantes');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (348,'0307013','Con técnica aséptica para hemocultivo automatizado, c/u, no incluye frasco');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (349,'0307014','Capilar ( adultos, niños y lactantes )');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (350,'0307016','Punción traqueal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (351,'0307017','Punción vesical en recién nacidos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (352,'0307018','Punción medular ósea');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (353,'0307023','Aspirados nasofaríngeo para adulto y niño.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (354,'0307024','Reacción cutánea a alergenos  (incluye el valor de los alergenos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (355,'0308001','Azúcares reductores (Benedict-Fehling o similar)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (356,'0308003','Grasas neutras (Sudán III)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (357,'0308004','Hemorragias ocultas, (bencidina, guayaco o test de Weber y similares), cualquier método, c/muestra');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (358,'0308005','Leucocitos fecales');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (359,'0308006','pH en deposiciones');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (360,'0308007','Elastasa fecal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (361,'0308009','Células neoplásicas en fluidos biológicos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (362,'0308010','Citológico c/s tinción (incluye prestacion al fresco, recuento celular y citológico porcentual)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (363,'0308011','Directo al fresco c/s tinción, (incluye trichomonas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (364,'0308012','Electrolitos (sodio, potasio, cloro), en exudados, secreciones y otros líquidos, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (365,'0308013','Eosinófilos en secreciones');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (366,'0308014','Físico-químico (incluye aspecto, color, pH, glucosa, proteína, Pandy y filancia)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (367,'0308015','Glucosa en exudados, secreciones y otros líquidos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (368,'0308016','Mucina, determinación de');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (369,'0308017','pH en exudados, secreciones y otros líquidos (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (370,'0308019','Proteínas, electroforésis de (incluye proteínas totales) en otros líquidos biológicos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (371,'0308020','Bandas oligoclonales (incluye electroforesis de L.C.R., suero e inmunofijación)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (372,'0308021','Glutamina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (373,'0308022','Índice IgG/albúmina (incluye determ. de IgG y albúmina en L.C.R. y suero)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (374,'0308023','Estudio de cristales (con luz polarizada)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (375,'0308025','Prueba de estimulación máxima con histamina, mínimo 5 muestras (no incluye la histamina ni el antihistamínico).');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (376,'0308029','Espermiograma (físico y microscópico, con o sin observación hasta 24 horas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (377,'0308030','Fosfatasa ácida prostática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (378,'0308031','Fructosa seminal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (379,'0308033','Células anaranjadas (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (380,'0308034','Contaminantes (meconio y sangre) (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (381,'0308035','Creatinina en exudados, secreciones y otros líquidos (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (382,'0308036','Fosfatidil glicerol y/o fosfatidil inositol');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (383,'0308037','Índice de bilirrubina (prueba de Liley)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (384,'0308038','Índice lecitina/esfingomielina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (385,'0308039','Madurez fetal completa (físico; células anaranjadas, bilirrubina, test de Clements, creatinina, contaminantes)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (386,'0308040','Test de Clements (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (387,'0308041','Colpocitograma');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (388,'0308043','Moco-semen, prueba de compatibilidad');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (389,'0308044','Flujo vaginal o secreción uretral, estudio de (incluye toma de muestra y códigos 03-06-004, 03-06-005, 03-06-008, 03-06-017 y 03-06-026)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (390,'0308045','Amilasa en Líquidos Biológicos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (391,'0308046','Lipasa en  Líquidos Biológicos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (392,'0308047','Esteatocrito');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (393,'0308049','Calprotectina cuantitativa por Elisa');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (394,'0308050','Proteínas totales en  exudados, secreciones y otros líquidos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (395,'0308051','Albúminas en  exudados, secreciones y otros líquidos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (396,'0309001','Acido ascórbico');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (397,'0309002','Acido delta aminolevulínico');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (398,'0309004','Ácido úrico en orina (cuantitativo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (399,'0309005','Acido 5 hidroxiindolacético cuantitativo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (400,'0309006','Amilasa cuantitativa en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (401,'0309007','Aminoácidos en orina (cualitativo)(excepto fenilalanina, PKU)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (402,'0309008','Calcio cuantitativo en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (403,'0309009','Cálculo urinario (prestacion físico y químico)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (404,'0309010','Creatinina cuantitativa en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (405,'0309011','Cuerpos cetónicos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (406,'0309012','Electrólitos (sodio, potasio, cloro) c/u, en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (407,'0309013','Microalbuminuria cuantitativa');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (408,'0309014','Gonadotrofina coriónica, sub-unidad beta en orina (test rápido)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (409,'0309015','Fósforo cuantitativo en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (410,'0309016','Glucosa (cuantitativo), en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (411,'0309035','Hemosiderina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (412,'0309017','Hidroxiprolina en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (413,'0309019','Mucopolisacáridos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (414,'0309020','Nitrógeno ureico o urea en orina (cuantitativo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (415,'0309021','Nucleótidos cíclicos (CAMP, CGM, u otros) c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (416,'0309022','Orina completa, (incluye cód. 03-09-023 y 03-09-024)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (417,'0309023','Orina, físico-químico ( aspecto, color, densidad, pH; proteínas, glucosa, cuerpos cetónicos, urobilinogeno, bilirrubina, hemoglobina y nitritos, determinación cualitativa o semi cuantitativa) todos o cada uno de los parámetros (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (418,'0309024','Sedimento de orina (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (419,'0309025','Osmolalidad');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (420,'0309027','Porfirinas, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (421,'0309028','Proteína (cuantitativa), en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (422,'0309029','Proteínas de Bence-Jones prueba térmica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (423,'0309034','Arsenico en orina (muestra aislada)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (424,'0309036','Cobre en orina');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (425,'0401001','Radiografía de las glándulas salivales "sialografía"');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (426,'0401002','Radiografía de partes blandas, laringe lateral, cavum rinofaríngeo (rinofarinx).');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (427,'0401004','Radiografía de tórax, proyección complementaria (oblicuas, selectivas u otras)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (428,'0401008','Radiografía de tórax  frontal o lateral con equipo móvil fuera del departamento de rayos.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (429,'0401009','Radiografía de tórax simple frontal o lateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (430,'0401070','Radiografía de tórax frontal y lateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (431,'0401010','Mamografía bilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (432,'0401110','Mamografía unilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (433,'0401130','Mamografía proyección complementaria  (axilar u otras)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (434,'0401011','Marcación preoperatoria de lesiones de la mama');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (435,'0401012','Radiografía de mama, pieza operatoria');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (436,'0401013','Radiografía de Abdomen Simple');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (437,'0401014','Radiografía de abdomen simple, proyección complementaria (lateral y/o oblicua)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (438,'0401015','Colangiografía intra o postoperatoria (por sonda T, o similar)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (439,'0401018','Enema baritado del colon (incluye llene y control post-vaciamiento)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (440,'0401019','Enema baritado del colon o intestino delgado, doble contraste');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (441,'0401020','Esofagograma  (incluye pesquisa de cuerpo extraño) (proc.aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (442,'0401021','Radiografía de esófago, estómago y duodeno, relleno y/o doble contraste');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (443,'0401022','Estudio radiológico de deglución faríngea');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (444,'0401023','Estudio radiológico del intestino delgado');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (445,'0401024','Radiografía de esófago, estómago y duodeno, simple en niños');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (446,'0401073','Videofluoroscopia para estudio de deglución');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (447,'0401027','Pielografía de eliminación o descendente: incluye renal y vesical simples previas, 3 placas post inyección de medio de contraste, controles de pie y cistografía pre y post miccional.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (448,'0401028','Radiografía renal simple (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (449,'0401029','Radiografía vesical simple o perivesical (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (450,'0401031','Radiografía de cavidades perinasales, órbitas, articulaciones temporomandibulares, huesos propios de la nariz, malar, maxilar, arco cigomático y cara');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (451,'0401032','Radiografía de cráneo frontal y lateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (452,'0401033','Radiografía de Cráneo  proyección especial de  base de cráneo (Towne)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (453,'0401035','Radiografía de oído, unilateral o bilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (454,'0401040','Radiografía de silla turca frontal y lateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (455,'0401042','Radiografía de columna cervical o atlas-axis (frontal y lateral)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (456,'0401043','Radiografía de columna cervical (frontal, lateral y oblicuas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (457,'0401044','Radiografía de columna cervical  flexión y  extensión (Dinámicas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (458,'0401045','Radiografía de columna dorsal o dorsolumbar localizada, parrilla costal adultos (frontal y lateral)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (459,'0401046','Radiografía columna lumbar o lumbosacra ( frontal, lateral y focalizada en el 5° espacio)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (460,'0401047','Radiografía columna lumbar o lumbosacra  flexión y  extensión (Dinámicas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (461,'0401048','Radiografía columna lumbar o lumbosacra, oblicuas adicionales');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (462,'0401049','Radiografía de columna total, panorámica con folio graduado  frontal o lateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (463,'0401051','Radiografía de pelvis, cadera o coxofemoral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (464,'0401151','Radiografía de pelvis, cadera o coxofemoral de RN, lactante o niño menor de 6 años.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (465,'0401052','Radiografía de pelvis, cadera o coxofemoral, proyecciones especiales; (rotación interna, abducción, lateral, Lawenstein u otras)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (466,'0401053','Radiografía de Sacrocoxis o articulaciones sacroilíacas.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (467,'0401054','Radiografía de brazo, antebrazo, codo, muñeca, mano, dedos, pie  (frontal y lateral)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (468,'0401055','Radiografía de clavícula.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (469,'0401056','Radiografía Edad Ósea: carpo y mano');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (470,'0401057','Radiografía Edad ósea : rodilla frontal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (471,'0401058','Estudio radiológico de escafoides');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (472,'0401059','Estudio radiológico de muñeca o tobillo frontal lateral y oblicuas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (473,'0401060','Radiografía de hombro, fémur, rodilla, pierna, costilla o esternón Frontal y Lateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (474,'0401062','Radiografía de Proyecciones especiales oblicuas u otras en hombro, brazo, codo, rodilla, rótulas, sesamoideos, axial de ambas rótulas o similares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (475,'0401063','Radiografía de túnel intercondíleo o radio-carpiano');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (476,'0401064','Apoyo fluoroscópico a procedimientos intraoperatorios y/o biopsia (no incluye el proc.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (477,'0402005','Galactografía, unilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (478,'0402008','Colangiopancreatografía endoscópica (a.c.18-01-018; 5-7 exp)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (479,'0402009','Fistulografía (a.c. 18-01-020) (3 exp.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (480,'0402011','Histerosalpingografía (a.c. 20-01-013) (4 exp.; incluye prueba de Cotte tardía)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (481,'0402012','Pielografía ascendente (a.c. 19-01-015) (3 exp.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (482,'0402014','Uretro y/o cistouretrografía miccional retrógrada (a.c. 19-01-016) ( 5 exp.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (483,'0402015','Artrografía facetaria');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (484,'0402019','Angiografía selectiva de carótida externa o interna (a.c 17-01-024 )');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (485,'0402020','Angiografía selectiva medular (a.c 17-01-024)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (486,'0402022','Angioplastia intraluminal coronaria. procedimiento radiológico. (a.c.17-01-031)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (487,'0402023','Angioplastia intraluminal periférica. procedimiento radiológico. (a.c. 17-01-032)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (488,'0402024','Aortografía con AOT o cineangiografía (a.c. 17-01-022)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (489,'0402025','Arteriografía de miembros superiores o inferiores unilateral (a.c.17-01-023)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (490,'0402027','Arteriografía selectiva con AOT o cineangiografía (pulmonar, renal, tronco celíaco o similar) c/u. (a.c. 17-01-024)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (491,'0402029','Arteriografía de vasos del cuello ( carótidas y vertebrales) (a.c. 11-01-013)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (492,'0402030','Cinecoronariografía (a.c. 17-01-019)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (493,'0402031','Embolización o balonización (a.c. de la angiografía correspondiente) (incluye control radiológico inmediato)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (494,'0402032','Instalación de catéter o sonda intracardíaca, control por radiólogo de (a.c. 17-01-020, 17-01-021, 17-01-011 o 17-01-014, según corresponda)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (495,'0402033','Ventriculografía derecha y/o izquierda (a.c. 17-01-011, 17-01-020 ó 17-01-021 ó 17-01-041 ó 17-01-42 ó 17-01-43, según corresponda)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (496,'0402035','Cavografía (a.c. 17-01-025)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (497,'0402038','Flebografía extremidad inferior o superior, unilateral (a.c. 17-01-026) cada extremidad.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (498,'0402040','Flebografía orbitaria o yugular (a.c. 11-01-015, 11-01-018 o 12-01-028 según corresponda), c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (499,'0402041','Flebografía selectiva de venas hepáticas, renales, gonadales, pélvicas. (a.c. 17-01-027)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (500,'0402050','Mielografía por punción lumbar con contraste hidrosoluble (a.c. 11-01-025)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (501,'0403001','Tomografía Computarizada de cráneo encefálica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (502,'0403002','Tomografía Computarizada de hipotálamo-hipófisis');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (503,'0403003','Tomografía Computarizada de fosa posterior');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (504,'0403006','Tomografía Computarizada de temporal-oído');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (505,'0403007','Tomografía Computarizada de órbitas maxilofacial');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (506,'0403008','Tomografía Computarizada de columna cervical');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (507,'0403018','Tomografía Computarizada de Columna Dorsal. Incluye mínimo 6 espacios');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (508,'0403019','Tomografía Computarizada de Columna Lumbar');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (509,'0403012','Tomografía Computarizada de cuello, partes blandas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (510,'0403013','Tomografía Computarizada de Tórax. Incluye además: Esternón, Clavículas, Articulación Acromioclavicular, Escápula, Costillas, Articulación Esternoclavicular. Incluye todo el Tórax o cada segmento o articulación. Incluye bilateralidad');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (511,'0403014','Tomografía Computarizada de abdomen (hígado, vías y vesícula biliar, páncreas, bazo, suprarrenales y riñones)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (512,'0403016','Tomografía Computarizada de Pelvis (Además incluye Sacro, Coxis, Caderas, Huesos Pélvicos, Articulaciones Sacro Ilíacas). Bilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (513,'0403020','Tomografía Computarizada de Abdomen y Pelvis');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (514,'0403021','Tomografía Computarizada Pielografía');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (515,'0403022','Tomografía Computarizada Urografía');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (516,'0403023','Tomografía Computarizada de Colonoscopía Virtual. No incluye instalación de sonda');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (517,'0403024','Tomografía Computarizada Planificación Radioterapia');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (518,'0403025','Tomografía Computarizada de Calcio Coronario');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (519,'0403104','Tomografía Computarizada Angio de Cuello');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (520,'0403105','Tomografía Computarizada Angio de Pelvis');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (521,'0403106','Tomografía Computarizada de Angio Cardíaco. Mínimo 64 cortes');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (522,'0403017','Tomografía Computarizada Musculoesquelética por zona anatómica. Por cada segmento o articulación: muslo, pierna, rodillas, antebrazo, codo, muñeca, mano, hombro, pie, tobillo u otros. Bilateral sólo para rodillas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (523,'0403101','Tomografía Computarizada angio  de encéfalo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (524,'0403102','Tomografía Computarizada angio de tórax');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (525,'0403103','Tomografía Computarizada angio de abdomen');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (526,'0403107','Tomografía computarizada angio de extremidades inferiores (bilateral)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (527,'0403108','Tomografía computarizada angio de extremidad superior (unilateral)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (528,'0404002','Ecografía obstétrica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (529,'0404003','Ecografía abdominal (incluye hígado, vía biliar, vesícula, páncreas, riñones, bazo, retroperitoneo y grandes vasos)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (530,'0404004','Ecografía como apoyo a cirugía, o a procedimiento (de tórax, muscular, partes blandas, etc.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (531,'0404005','Ecografía transvaginal o transrectal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (532,'0404006','Ecografía ginecológica, pelviana femenina u obstétrica con estudio fetal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (533,'0404007','Ecografía transvaginal para seguimiento de ovulación, procedimiento completo (6-8 sesiones )');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (534,'0404008','Ecografía para seguimiento de ovulación, procedimiento completo (6 a 8 sesiones)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (535,'0404009','Ecografía pélvica masculina (incluye vejiga y próstata)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (536,'0404010','Ecografía renal (bilateral), o de bazo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (537,'0404011','Ecografía encefálica (RN o lactante)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (538,'0404012','Ecografía mamaria bilateral (incluye Doppler)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (539,'0404013','Ecografía ocular, unilateral o bilateral.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (540,'0404014','Ecografía testicular (unilateral o bilateral) (Incluye Doppler)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (541,'0404015','Ecografía tiroidea (Incluye Doppler)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (542,'0404016','Ecografía Partes Blandas o Musculoesquelética (cada zona anatómica)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (543,'0404118','Ecografía vascular (arterial y venosa) periférica (bilateral)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (544,'0404119','Ecografía doppler de vasos del cuello');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (545,'0404120','Ecografía transcraneana');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (546,'0404121','Ecografía abdominal o de vasos testiculares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (547,'0404122','Ecografía doppler de vasos placentarios');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (548,'0404218','Elastografía hepática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (549,'0405001','Resonancia Magnética Cráneo Encefálica u Oídos, bilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (550,'0405002','Resonancia Magnética de hipotálamo - hipófisis');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (551,'0405003','Resonancia Magnética  de órbitas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (552,'0405004','Resonancia Magnética de articulaciones temporomandibulares');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (553,'0405005','Resonancia Magnética  de columna cervical');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (554,'0405006','Resonancia Magnética de columna dorsal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (555,'0405007','Resonancia Magnética de columna lumbar');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (556,'0405017','Resonancia Magnética Angiografía de Encéfalo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (557,'0405018','Resonancia Magnética Angiografía de Cuello');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (558,'0405019','Resonancia Magnética Angiografía de Tórax');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (559,'0405020','Resonancia Magnética Angiografía de Abdomen');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (560,'0405021','Resonancia Magnética Angiografía de Pelvis');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (561,'0405022','Resonancia Magnética  Angiografía de Extremidad Superior Unilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (562,'0405023','Resonancia Magnética  Angiografía de Extremidad Inferior Bilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (563,'0405009','Resonancia Magnética de Tórax ( corazón, esternón, clavículas, articulación acromioclavicular, escápula, costillas o articulación esternoclavicular). Toda la pared torácica o cada segmento o articulación. Bilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (564,'0405010','Resonancia Magnética de abdomen');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (565,'0405011','Resonancia Magnética de Pelvis. Incluye: osteoarticular de sacroiliacas u osteoarticular de sacrocoxis u osteoarticular de huesos pélvicos u órganos pelvianos (incluye genitales internos y gastrointestinal)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (566,'0405012','Resonancia Magnética de abdomen y pelvis');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (567,'0405098','Colangioresonancia');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (568,'0405013','Resonancia Magnética de rodilla');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (569,'0405024','Resonancia Magnética de Mano o Muñeca');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (570,'0405025','Resonancia Magnética de Antebrazo o Brazo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (571,'0405026','Resonancia Magnética de Codo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (572,'0405027','Resonancia Magnética de Hombro');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (573,'0405028','Resonancia Magnética de Pie, Antepie o Tobillo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (574,'0405029','Resonancia Magnética de Pierna');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (575,'0405030','Resonancia Magnética de Muslo o Cadera. Unilateral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (576,'0405031','Resonancia Magnética de Mama (bilateral)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (577,'0405032','Resonancia Magnética Fetal');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (578,'0405016','Resonancia Columna Total (cervical, dorsal, lumbar)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (579,'0501100','Captación I-131 a las 2 y/o 24 horas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (580,'0501101','Cintigrafía tiroidea, cualquier radioisótopo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (581,'0501102','Cintigrafía  glándulas paratiroides (no incluye MIBI)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (582,'0501104','Cintigrafía ósea trifásica (incluye mediciones fase precoz y tardía)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (583,'0501136','Cintigrafía ósea completa planar');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (584,'0501137','Cintigrafía de médula ósea');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (585,'0501105','Spect de perfusión miocárdica estrés y reposo (no incluye honorarios médico cardiólogo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (586,'0501106','Ventriculografía cardiaca isotópica de equilibrio con glóbulos rojos');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (587,'0501107','Pool sanguíneo, arteriografía isotópica c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (588,'0501108','Linfocintigrafía isotópica (no incluye procedimiento)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (589,'0501109','Pool sanguíneo spect');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (590,'0501111','Estudio motilidad esofágica y/o reflujo gastroesofágico');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (591,'0501112','Vaciamiento gástrico líquido o sólido');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (592,'0501113','Cintigrafía vesícula y vía biliar');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (593,'0501114','Detección de sitio de sangramiento digestivo con glóbulos rojos marcados');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (594,'0501115','Detección divertículo Meckel');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (595,'0501116','Spect hepatoesplénico, evaluación hemangioma o hiperplasia (incluye mediciones fase precoz y tardía)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (596,'0501138','Cintigrafía de glándulas salivales');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (597,'0501139','Dacriocintigrafía');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (598,'0501117','Cintigrafía renal con D.M.S.A.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (599,'0501118','Estudio dinámico renal con Tc 99 - DTPA');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (600,'0501119','Estudio dinámico renal con Tc 99 - MAG 3 o EC');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (601,'0501120','Cistografía isotópica indirecta');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (602,'0501121','Cistografía isotópica directa, a.c. 19-01-022');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (603,'0501122','Cintigrafía pulmonar perfusión o ventilación o difusión, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (604,'0501123','Cintigrafía y estudio aspiración pulmonar');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (605,'0501124','Spect cerebral de perfusión (no incluye radiofármaco)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (606,'0501125','Estudio dinámico sistema nervioso (radiocisternografia, fístula L.C.R, radioventriculografía, control válvula derivativa, sub-durografía isotópica), c/u (no incluye procedimiento).');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (607,'0501126','Cintigrafía evaluación infecciones (leucocitos, infecton, granulocitos u otros) (no incluye radiofármaco ni procedimiento).');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (608,'0501127','Cintigrafía con galio-67 planar infección (no incluye radioisótopo) (a.c. 0501133, cuando corresponda)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (609,'0501128','Detección y/o marcación de ganglio centinela, no incluye, punción ni detección con gammaprobe');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (610,'0501129','Cintigrafía con galio-67 planar y Spect, para estudio de tumores (no incluye radioisótopo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (611,'0501130','Exploración sistémica con I-131 (incluye mediciones fase precoz y tardía)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (612,'0501131','Estudio glándulas mamarias (mamocintigrafia) (no incluye MIBI)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (613,'0501132','Estudio de tumores (anticuerpos monoclonales, octreoscan, DMSA pentavalente, prostacint u otros) (no incluye radioisótopo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (614,'0501133','Spect - Tomografía por emisión fotón único, cualquier órgano (no incluye radioisótopo)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (615,'0501134','Densitometría ósea a fotón doble, columna y cadera (unilateral o bilateral) o cuerpo entero');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (616,'0501135','PET-CT');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (617,'0502001','Dosis terapéuticas con I-131 hasta 30 mCi.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (618,'0502002','Dosis terapéuticas con I-131 entre 31 a 100 mCi.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (619,'0502003','Dosis terapéuticas con I-131 entre 101 a 200 mCi.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (620,'0502004','Dosis terapéuticas con I-131 entre 201 a 300 mCi.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (621,'0502005','Terapia paliativa del dolor con radioisótopos (no incluye radiofármaco)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (622,'0601101','Evaluación Kinesiológica Integral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (623,'0601102','Atención Kinesiológica Integral Ambulatoria o Domiciliaria');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (624,'0601103','Atención Kinesiológica Integral en Pacientes hospitalizados');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (625,'0601104','Atención Kinesiológica Integral UPC (Intensivo e Intermedio)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (626,'0602001','Atención integral de terapia ocupacional');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (627,'0602002','Intervención de terapia ocupacional en ayudas técnicas y tecnología asistida');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (628,'0602003','Intervención terapia ocupacional en actividades de la vida diaria, básicas, instrumentales y avanzadas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (629,'0608101','Telerehabilitación: Evaluación Kinesiológica Integral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (630,'0608102','Telerehabilitación: Atención Kinesiológica Integral');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (631,'0608201','Telerehabilitación: Atención integral de terapia ocupacional');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (632,'0608202','Telerehabilitación: Intervención de terapia ocupacional en ayudas técnicas y tecnología asistida');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (633,'0608203','Telerehabilitación: Intervención terapia ocupacional en actividades de la vida diaria, básicas, instrumentales y avanzadas');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (634,'0702101','Producción de glóbulo rojo');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (635,'0702102','Producción de concentrado de plaquetas estándar');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (636,'0702103','Producción de plasma o crioprecipitado');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (637,'0702104','Producción de concentrado de plaquetas por aféresis automática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (638,'0702105','Producción de concentrado de glóbulos rojos por aféresis automática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (639,'0702106','Producción de concentrado de  leucocitos por aféresis automática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (640,'0702107','Producción de concentrado de  plasma por aféresis automática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (641,'0702108','Producción de células progenitoras hematopoyética por aféresis automática a partir de sangre periférica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (642,'0702109','Irradiación de componente sanguíneo por unidad');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (643,'0702110','Filtración de glóbulos rojos o plaquetas (incluye filtro Recién Nacido y pool de plaquetas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (644,'0702201','Calificacion microbiologica por donante estudiado, componente sanguíneo producido o producto de aféresis automática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (645,'0702202','Calificación inmunohematológica por donante estudiado , componente sanguíneo producido o producto de aféresis automática');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (646,'0702203','Prueba de compatibilidad por unidad de glóbulos rojos estudiada (proc. aut.)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (647,'0702204','Fenotipificación otros grupos sanguíneos por unidad de glóbulos rojos producido');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (648,'0702205','Titulación de anticuerpos irregulares eritrocitarios');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (649,'0702206','Genotipificación D variante (incluye D parcial y débil)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (650,'0702207','Detección de anticuerpos irregulares eritrocitarios');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (651,'0702208','Grupos menores. Tipificación o determinación de otros sistemas sanguíneos (Kell, Duffy, Kidd y otros) c/u.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (652,'0702209','Subgrupo ABO y Rh fenotipo - genotipo Rh, c/u');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (653,'0702301','Transfusión en adulto por unidad o subunidad de glóbulos rojos o unidad / subunidad o pool de: plasma, plaquetas o crioprecipitados (atención ambulatoria, atención cerrada siempre que la administración sea controlada por profesional especialista, tecnólogo médico o médico responsable)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (654,'0702302','Transfusión en niño por unidad o subunidad de glóbulos rojos, o unidad/subunidad o pool de: plasma, plaquetas o crioprecipitados (atención ambulatoria, atención cerrada siempre que la administración sea controlada por profesional especialista, tecnólogo médico o médico responsable)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (655,'0702303','Transfusión por unidad de glóbulos rojos, o unidad o pool de: plasma, plaquetas o crioprecipitados, en adulto o niño en pabellón (con asistencia permanente del médico o tecnologo médico responsable)(no corresponde su cobro cuando sea controlada por médico anestesista, por estar incluida en el valor de sus honorarios)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (656,'0702304','Sangría (considera el cobro de una prestación por cada unidad de sangre extraída)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (657,'0702305','Recambio plasmático por aféresis terapéutica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (658,'0702306','Depleción leucocitaria por aféresis terapéutica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (659,'0702307','Depleción plaquetaria por aféresis terapéutica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (660,'0702308','Eritroféresis por aféresis terapéutica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (661,'0702309','Fotoféresis terapéutica');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (662,'0703001','Búsqueda e identificación de donante no emparentado de precursores hematopoyéticos en registros de donantes y bancos de sangre de cordón umbilical');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (663,'0703002','Exámenes confirmatorios de idoneidad de donante no emparentado de precursores hematopoyéticos incluyendo sangre de cordón umbilical');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (664,'0703003','Procuramiento de injerto de precursores hematopoyéticos de medula osea o sangre periferica (Banco Internacional)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (665,'0703004','Procuramiento de injerto de precursores hematopoyéticos de sangre de cordon umbilical (Banco Internacional)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (666,'0703005','Procuramiento de injerto de precursores hematopoyéticos de medula osea o sangre periferica (Banco Nacional)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (667,'0703006','Adquisición  de injerto sangre de cordón (Banco Nacional)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (668,'0801001','Citodiagnóstico corriente, exfoliativa (Papanicolau) (por cada placa)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (669,'0801002','Citología no ginecológica (por cada placa o frasco) (máximo 6)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (670,'0801003','** Estudio histopatológico con microscopia electrónica (por cada grilla)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (671,'0801004','** Estudio histopatológico con técnicas de inmunohistoquímica o inmunofluorescencia (por cada anticuerpo investigado)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (672,'0801005','** Estudio histopatológico con técnicas histoquímicas, niveles, decalcificación (por cada lámina)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (673,'0801006','Consulta intraoperatoria (por cada muestra / tejido o asistencia a pabellón) (no incluye biopsia diferida)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (674,'0801007','Estudio histopatológico con tinción corriente de biopsia diferida con estudio seriado (mínimo 10 muestras) de un órgano o parte de él (no incluye estudio con técnica habitual de otros órganos incluidos en la muestra)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (675,'0801008','Estudio histopatológico de biopsia diferida (por cada muestra y/o tejido) (incluye hasta 3 láminas)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (676,'0801009','Necropsia de adulto o niño, con estudio histopatológico corriente.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (677,'0801010','Necropsia de feto o recién nacido, con estudio histopatológico corriente.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (678,'0801011','PCR tiempo real para marcadores tumorales en cortes histológicos (incluye microdisección y extracción de ADN)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (679,'0801012','Técnica inmunohistoquimica para marcadores tumorales ( ALK-PDL1-ROS1)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (680,'0901001','Control paciente psiquiátrico crónico;máx.2 controles al mes');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (681,'0901002','Desintoxicación o deshabituación en pacientes hospitalizados (incluye tratamiento de la intoxicación, del síndrome de privación y de las complicaciones médicas); por día ( máximo 15 )');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (682,'0901003','Sesión de terapia electroconvulsivante (hasta 6 sesiones por ciclo o sesiones de mantención) c/ sesión');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (683,'0901005','Atención psiquiátrica o psicoterapia de familia, individual, de relajación o de manejo (con familia u otros);(cada sesión mínimo 45'')');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (684,'0901010','Psicoterapia de pareja (por cada miembro de la pareja)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (685,'0902001','Consulta Psicólogo clínico (sesiones 45'')');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (686,'0902002','Psicoterapia Individual');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (687,'0902003','Sesión de psicoterapia de pareja (con ambos miembros)');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (688,'0902010','Test de Rorschach');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (689,'0902011','Test de relaciones objetales');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (690,'0902012','Test de Apercepción Temática, T.A.T., C.A.T.-H o C.A.T.-A.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (691,'0902013','Test de Edwards');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (692,'0902014','Test de M.M.P.I.');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (693,'0902015','Test de Wechsler, WAIS, WISC ó WPPSI');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (694,'0902016','Test de Dominó o Test de Raven');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (695,'0902017','Test de Bender');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (696,'0902018','Bender Bip');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (697,'0902019','Test de Goldstein');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (698,'0902020','Test de Luria-Nebraska');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (699,'0908101','Telerehabilitación: Psicólogo clínico (sesiones 45'')');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (700,'0908102','Telerehabilitación: Psicoterapia Individual');
INSERT INTO prestaciones(id,codigo,prestacion) VALUES (701,'0908103','Telerehabilitación: Sesión de psicoterapia de pareja (con ambos miembros)');